### ISSUE TITLE
How to achieve the fine-tune result?

### ISSUE THREAD

**Issue by Ynjxsjmh** [XinhaoMei/audio-text_retrieval#1]
Currently I'm using to following `settings.yaml`, modification is to change `cnn_encoder.pretrained` to `Yes`. I only ensure `./pretrained_models/audio_encoder/ResNet38.pth` exists, I don't have `path.word2vec`.

<details>
<summary>
Click to view `settings.yaml`
</summary>

```
mode: 'train'
exp_name: 'exp'
dataset: 'AudioCaps'
text_encoder: 'bert'
joint_embed: 1024

wav:
  sr: 32000
  window_size: 1024
  hop_length: 320
  mel_bins: 64

bert_encoder:
  type: 'bert-base-uncased'
  freeze: Yes

cnn_encoder:
  model: 'ResNet38'
  pretrained: Yes
  freeze: Yes

data:
  batch_size: 64
  num_workers: 8

training:
  margin: 0.2
  freeze: Yes
  loss: contrastive  # 'triplet', 'weight', 'ntxent'
  spec_augmentation: Yes
  epochs: 50
  lr: !!float 1e-4
  clip_grad: 2
  seed: 20
  resume: No
  l2_norm: Yes
  dropout: 0.2

path:
  vocabulary: 'data/{}/pickles/words_list.p'
  word2vec: 'pretrained_models/w2v_all_vocabulary.model'
  resume_model: ''
```
</details>

The best results in 50 epoches is 

```python
Caption to audio: r1: 16.96, r5: 47.81, r10: 65.99, r50: 92.23, medr: 6.00, meanr: 17.94
Audio to caption: r1: 24.09, r5: 54.05, r10: 71.66, r50: 94.94, medr: 5.00, meanr: 13.57
```

which couldn't reach the fine-tune result shown in your [paper](https://arxiv.org/abs/2203.15537):

![image](https://user-images.githubusercontent.com/40143136/169069677-e865a4a5-99bd-404d-aaa6-50e534b7da2a.png)

I go through the paper but fail to find the detail about fine-tune. Would you mind elaborating this?
