### ISSUE TITLE
Cannot get similar results for CNN14+BERT

### ISSUE THREAD

**Issue by geniusturtle6174** [XinhaoMei/audio-text_retrieval#2]
I am trying to reproduce the results of "CNN14+BERT", but the obtained results are significantly different from that shown in the tech report. I would like to know if I did anything wrong.

The config I used is:
```
mode: 'train'
exp_name: 'exp'
dataset: 'Clotho'
text_encoder: 'bert'
joint_embed: 1024

wav:
  sr: 32000 
  window_size: 1024
  hop_length: 320
  mel_bins: 64

bert_encoder:
  type: 'bert-base-uncased'
  freeze: Yes

cnn_encoder:
  model: 'Cnn14'
  pretrained: Yes
  freeze: Yes

data:
  batch_size: 64
  num_workers: 0

training:
  margin: 0.2
  freeze: Yes
  loss: ntxent  # 'triplet', 'weight', 'ntxent'
  spec_augmentation: Yes
  epochs: 50
  lr: !!float 1e-4
  clip_grad: 2
  seed: 20
  resume: No
  l2_norm: Yes
  dropout: 0.2

path:
  vocabulary: 'data/{}/pickles/words_list.p'
  word2vec: 'pretrained_models/w2v_all_vocabulary.model'
  resume_model: ''
```

Finally I got:
```
Caption to audio: r1: 7.69, r5: 24.38, r10: 36.11, r50: 69.15, medr: 20.00, meanr: 63.24
```

But the results of CNN14+BERT in the tech report is:
```
R@1: 0.147, R@5: 0.377,  R@10: 0.495
```
